### ISSUE TITLE
How do you setup Card-Jitsu?

### ISSUE THREAD

**Issue by DidUJustHitDat** [Zaseth/KITSUNE-MODIFIED#11]
I installed the source, ran the run.php file but card-jitsu doesn't work. When trying to battle against my 2nd account, Its stuck loading on this screen: 

![Card Jitsu](https://image.prntscr.com/image/-fOFNefCTeqaHGPjOydtvg.png)

**Comment by DidUJustHitDat** [comment]
Apparently, it might be a SWF problem? Can you please send us the working Card-Jitsu swf files.

**Comment by Zaseth** [comment]
You can't use 2 accounts on this source as far as I know, i'll attach the cj files right now.
