### ISSUE TITLE
Card Jitsu won't load.

### ISSUE THREAD

**Issue by OliverBoy** [Zaseth/KITSUNE-MODIFIED#4]
Before you say this is my fault, someone else I know is also having this problem.

Card Jitsu is stuck loading.
https://i.imgur.com/tbRpUfFh.jpg

**Comment by olivierek6** [comment]
having this problem too. the network tab is empty, no errors!

**Comment by Zaseth** [comment]
You can't play with Sensei. I forgot to say that I did not code this Card-Jitsu and I won't even waste my time on learning it.

**Comment by olivierek6** [comment]
It happens with playera too. its not sensei

14.10.2017 8:37 PM "Zaseth" <notifications@github.com> napisał(a):
